name: .NET Core

on: [push, pull_request]  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore **/*.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore **/*.sln
    - name: Test
      run: dotnet test --no-restore --verbosity normal **/*.sln
    - name: Create package
      run: dotnet pack -p:PackageVersion=4.2.0 -v normal -c Release --no-restore Lindhart.Utility.IO.Streaming/Streaming/Streaming.csproj
    - name: Upload package as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NuGetPackage
        path: ./Lindhart.Utility.IO.Streaming/Streaming/bin/Release/*.nupkg
